javascripts:
  dev:
    - 'Initialize'
    - 'utils/Log'
    - 'utils/Array'
    - 'utils/Object'
    - 'utils/Class'
    - 'events/Delegate'
    - 'utils/Math'
    - 'utils/String'
    - 'utils/Date'
    - 'utils/Element'
    - 'utils/Lang'
    - 'utils/Toggler'
    - 'utils/TreeCrawler'
    - 'utils/ClassToggler'
    - 'events/Event'
    - 'math/Point'
    - 'math/Rectangle'
    - 'dom/ElementBuilder'
    - 'dom/Selector'
    - 'net/Ajax'
    - 'net/Controller'
    - 'net/Route'
    - 'net/Router'
    - 'data/List'
    - 'data/Queue'
    - 'events/Channel'
    - 'events/Clock'
    - 'events/ElementEvent'
    - 'events/Timeline'
    - 'events/Timeout'
    - 'model/Base'
    - 'model/List'
    - 'model/LocalStorage'
    - 'transition/Base'
    - 'transition/Blind'
    - 'transition/Fade'
    - 'spec/matcher/Base'
    - 'spec/matcher/A'
    - 'spec/matcher/Contain'
    - 'spec/matcher/Eq'
    - 'spec/matcher/False'
    - 'spec/matcher/Null'
    - 'spec/matcher/Receive'
    - 'spec/matcher/True'
    - 'spec/node/Base'
    - 'spec/node/AutoExec'
    - 'spec/node/Before'
    - 'spec/node/Context'
    - 'spec/node/Describe'
    - 'spec/node/It'
    - 'spec/node/Specify'
    - 'spec/runner/Base'
    - 'spec/runner/Real'
    - 'spec/runner/Dry'
    - 'spec/view/Base'
    - 'spec/view/Browser'
    - 'spec/Actual'
    - 'spec/Api'
    - 'spec/Mock'
    - 'spec/Receiver'
    - 'spec/Result'
    - 'spec/Spec'
    - 'template/Base'
    - 'template/Compiler'
    - 'template/Helpers'
    - 'template/Library'
    - 'component/Base'
    - 'component/Button'
    - 'component/Calendar'
    - 'component/CheckBox'
    - 'component/Link'
    - 'component/Select'
    - 'component/Table'
    - 'component/Text'
    - 'component/Tree'
    - 'component/utils/EventHandler'
    - 'component/utils/Scanner'
    - 'component/utils/Sweeper'
    - 'ui/ElementInspector'
    - 'view/Base'
    - 'view/Input'
    - 'view/List'
    - 'view/DatePicker'
    - 'view/Template'
    - 'Shortcuts'
    - 'Finalize'
stylesheets:
  dev: 'artjs'
